In [47]:
import pandas as pd
from openpyxl import load_workbook
from typing import Iterable
from pydantic import BaseModel, ConfigDict
pd.set_option('display.max_columns', None)

# **Classes**

In [50]:
class SecondaryTable(BaseModel):
    model_config=ConfigDict(arbitrary_types_allowed=True)
    sheet_name: str
    describe_title: str
    table: pd.DataFrame

# **Functions**

In [14]:
def get_sheetnames_xlsx(filepath):
    wb = load_workbook(filepath, read_only=True, keep_links=False)
    return wb.sheetnames

In [ ]:
def load_secondary_tables(path: str, secondary_tables: Iterable):
    for st in secondary_tables:
        df = pd.read_excel(path, engine='openpyxl', sheet_name=st)
        df_p = df.iloc[1:]
        df_p.columns = df.iloc[0].list()
        describe_title = df.columns[0]
        SecondaryTable(
            sheet_name=st,
            describe_title=describe_title,
            
        )

# **values**

In [45]:
path_1_20 = './datasets/source_LDB_datasets/1_20_.xlsx'
processed_path_1_20 = './datasets/processed_LDB_datasets/1_20_.xlsx'
main_sheet_name = 'Sheet1'

# **sheets**

In [16]:
sheets = get_sheetnames_xlsx(path_1_20)

In [11]:
df_samples = pd.read_excel(path_1_20, engine='openpyxl', sheet_name=sheets[0])

In [44]:
pd.read_excel(path_1_20, engine='openpyxl', sheet_name=sheets[2])

    Объекты модели - Серии проектов (323)     Unnamed: 1
0                                      ID           NAME
1                                 2048743  не определено
2                                 2048744           КОПЭ
3                                 2048745         П-3/22
4                                 2048746            П-4
..                                    ...            ...
290                             399086155       И-2947-9
291                             399086156       И-2947-8
292                             399086157      И-2947-10
293                             462314920          П111М
294                             503740409          И-515

[295 rows x 2 columns]

In [38]:
first_col_names = df_samples.columns
second_col_names = df_samples.iloc[0]
extended_columns = second_col_names[second_col_names.index.map(lambda a: 'COL' in a)]
not_extended_columns = first_col_names[first_col_names.map(lambda a: 'COL' not in a)]
columns = not_extended_columns.to_list() + extended_columns.to_list()
processed_dataset = df_samples.iloc[1:].copy()
processed_dataset.columns = columns

In [42]:
processed_dataset

,ID,NAME,PARENT_ID,LOGIN,Назначение,Форма собственности,Год постройки,Год реконструкции,Серия проекта,Количество этажей,Количество подъездов,Количество квартир,Общая площадь,Общая площадь жилых помещений,Общая площадь нежилых помещений,Строительный объем,Износ объекта (по БТИ),Класс энергоэффективности,Материал стен,Признак аварийности здания,Количество пассажирских лифтов,Количество грузопассажирских лифтов,Очередность уборки кровли,Материал кровли,UNOM,Вид социального объекта,Тип жилищного фонда,Статус МКД,Статус управления МКД,Количество грузовых лифтов,Причина Изменения Статуса МКД,Категория МКД
1,1500923.0,"Дом по адресу Красковская ул., д.121А",NaN,WS,NaN,NaN,1956,NaN,2048798,1,2,1,76,76,0,NaN,NaN,NaN,179625102,22728486,0,0,NaN,22289204,49928,NaN,22741963,58761330,NaN,0,NaN,NaN
2,1500933.0,"Дом по адресу Байкальская ул., д.18, к.2",NaN,WS,NaN,NaN,2005,NaN,2048798,18,2,148,8266,8220,46,NaN,NaN,NaN,179625111,22728486,2,2,NaN,22289201,64148,NaN,42875644,58761330,45063584,0,NaN,NaN
3,1500943.0,"Дом по адресу Перовская ул., д.48",NaN,WS,NaN,NaN,1955,NaN,2048912,4,2,20,1240,1070,170,NaN,NaN,NaN,179625102,22728486,0,0,22289162,22289204,19485,NaN,42875644,58761330,45063584,0,NaN,NaN
4,1500951.0,"Дом по адресу Парковая 3-я ул., д.39, к.3",NaN,404070001,NaN,NaN,1960,NaN,2048912,5,3,60,2518,2492,26,NaN,NaN,NaN,179625102,22728486,0,0,22289162,22289201,18533,NaN,42875644,58761330,45063584,0,NaN,NaN
5,1500954.0,"Дом по адресу Свободный просп., д.11, к.2",NaN,WS,NaN,NaN,1973,NaN,2048755,9,12,431,21103,21088,15,0,0,NaN,2048929,22728486,12,0,NaN,22289201,22830,NaN,42875644,58761330,45063584,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3636,1527340.0,"Дом по адресу Алтайская ул., д.21",NaN,operator2,NaN,NaN,2004,NaN,2048860,17,3,201,9440,9318,122,0,0,NaN,2048929,22728486,3,3,NaN,22289201,240008,NaN,42875644,58761330,45063584,0,NaN,NaN
3637,1527351.0,"Дом по адресу Красковский 1-й пр., д.2",NaN,404080001,NaN,NaN,1939,NaN,2048798,2,4,4,307,307,0,NaN,NaN,NaN,2048931,22728486,0,0,NaN,22289204,50002,NaN,22741963,58761330,NaN,0,NaN,NaN
3638,1527357.0,"Дом по адресу Барабанный пер., д.11",NaN,404150001,NaN,NaN,1938,NaN,2048798,2,2,2,806,770,36,NaN,NaN,NaN,179625102,22728486,0,0,NaN,22289204,1437,NaN,42875644,58761330,45063584,0,Распоряжение МЖИ №7793-РЛ дата 14.08.2020,NaN
3639,1527359.0,"Дом по адресу Яузская аллея, д.6",NaN,404010001,NaN,NaN,1958,NaN,2048912,5,3,60,4472,4137,335,0,0,NaN,179625102,22728486,0,0,22289163,22289204,29467,NaN,42875644,58761330,45063584,0,NaN,NaN
3640,1527366.0,"Дом по адресу Поселковая ул., д.10",NaN,WS,NaN,NaN,1937,NaN,2048798,1,4,3,141,141,0,NaN,NaN,NaN,2048931,22728486,0,0,NaN,22289204,49823,NaN,22741963,58761330,NaN,0,NaN,NaN

{'COL_754': 'Назначение',
 'COL_755': 'Форма собственности',
 'COL_756': 'Год постройки',
 'COL_757': 'Год реконструкции',
 'COL_758': 'Серия проекта',
 'COL_759': 'Количество этажей',
 'COL_760': 'Количество подъездов',
 'COL_761': 'Количество квартир',
 'COL_762': 'Общая площадь',
 'COL_763': 'Общая площадь жилых помещений',
 'COL_764': 'Общая площадь нежилых помещений',
 'COL_765': 'Строительный объем',
 'COL_766': 'Износ объекта (по БТИ)',
 'COL_767': 'Класс энергоэффективности',
 'COL_769': 'Материал стен',
 'COL_770': 'Признак аварийности здания',
 'COL_771': 'Количество пассажирских лифтов',
 'COL_772': 'Количество грузопассажирских лифтов',
 'COL_775': 'Очередность уборки кровли',
 'COL_781': 'Материал кровли',
 'COL_782': 'UNOM',
 'COL_2156': 'Вид социального объекта',
 'COL_2463': 'Тип жилищного фонда',
 'COL_3163': 'Статус МКД',
 'COL_3243': 'Статус управления МКД',
 'COL_3363': 'Количество грузовых лифтов',
 'COL_3468': 'Причина Изменения Статуса МКД',
 'COL_103506': 'Категория МКД'}